config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :rooms do
  	resources :reviews
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations" }
  root 'pages#info'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
    @booking.room = @room
    @booking.user = current_user
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
    @booking.user = current_user
    @booking.room = @room
    @booking.user = current_user
    
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)
    @booking.user_id = current_user.id

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    if current_user.id == @booking.user.id
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
    else
    redirect_to root_path, notice: "You don't have permission."
    end
   end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:start_date, :end_date, :price, :totalprice, :room_id, :user_id)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= form_with(model: booking, local: true) do |form| %>
  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date, id: :booking_start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_select :end_date, id: :booking_end_date %>
  </div>

  <div class ="field">
      <%= form.hidden_field :price, value: @room.price, id: 'booking_price' %>
  </div>

   <div class ="field">
      <%= form.hidden_field :totalprice, id: 'booking_totalprice' %>
  </div>


  <div class="field">
        <%= form.hidden_field :room_id, value: @room.id %>
    </div>

    <div class="field">
          <%= form.hidden_field :user_id, value: current_user.id %>
      </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>


<script>
$('select').on('change',function(){
y1 = $('#booking_start_date_1i').val()
y2 = $('#booking_end_date_1i').val()
m1 = $('#booking_start_date_2i').val()
m2 = $('#booking_end_date_2i').val()
d1 = $('#booking_start_date_3i').val()
d2 = $('#booking_end_date_3i').val()
var date2 = new Date(y1, m1, d1);
var date1 = new Date(y2, m2, d2);

var diff = date1 - date2;
var days = diff / 1000 / 60 / 60 / 24;
$('#booking_totalprice').val(days*$('#booking_price').val())
});
</script>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<h1>Bookings</h1>

<table>
  <thead>
    <tr>
      <th>Start date</th>
      <th>End date</th>
      <th>Price</th>
      <th>Total Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.start_date %></td>
        <td><%= booking.end_date %></td>
        <td><%= booking.price %></td>
        <td><%= booking.totalprice %></td>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_booking_path %>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<p>
  <strong>Start date:</strong>
  <%= @booking.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @booking.end_date %>
</p>

<p>
  <strong>Price:</strong>
  <%= @booking.price %>
</p>

<p>
  <strong>Total Price:</strong>
  <%= @booking.totalprice %>
</p>


<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>