config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :rooms do
  	resources :reviews
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations" }
  root 'pages#info'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :reviews
  has_many :bookings

  geocoded_by :location
  after_validation :geocode, :if => :location_changed?

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "300x300>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
<<<<<<< HEAD
  @rooms = current_user.rooms
=======
>>>>>>> dce26c2f005a04950d404bd3be009bc50f2e0b5f
  if params[:search].present?
    @rooms = Room.near(params[:search], 50, :order => :distance)
  else
    @rooms = Room.all
  end
end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @booking = Booking.new
    @reviews = @room.reviews
    @average_review = if @reviews.blank?
      0
    else
      @room.reviews.average(:rating)
  end
end

  # GET /rooms/new
  def new
    @room = current_user.rooms.build
  end

  # GET /rooms/1/edit
  def edit
    if current_user.id != @room.user.id
    redirect_to root_path, notice: "You don't have permission."
    end
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)
    @room.user_id = current_user.id if current_user
    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    if current_user.id == @room.user.id
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
   else
   redirect_to root_path, notice: "You don't have permission."
  end
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit( :price, :host_name, :room_id, :room_name, :description, :country, :location, :bed, :bathroom, :capacity, :pets, :smoking, :wifi, :avatar, :user_id)
    end
  end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<%= form_tag rooms_path, :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search Near", :name => nil %>
  </p>
<% end %>

<table>
  <thead>
    <tr>
      <th>Price</th>
      <th>Host Name</th>
      <th>Room name</th>
      <th>Description</th>
      <th>Country</th>
      <th>Location</th>
      <th>Bed</th>
      <th>Bathroom</th>
      <th>Capacity</th>
      <th>Pets</th>
      <th>Smoking</th>
      <th>Wifi</th>
      <th>Date Created</th>
       <th>Updated</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.price %></td>
        <td><%= room.host_name %></td>
        <td><%= room.room_name %></td>
        <td><%= room.description %></td>
        <td><%= room.country %></td>
        <td><%= room.location %></td>
        <td><%= room.bed %></td>
        <td><%= room.bathroom %></td>
        <td><%= room.capacity %></td>
        <td><%= room.pets %></td>
        <td><%= room.smoking %></td>
        <td><%= room.wifi %></td>
        <td><%= time_ago_in_words(room.created_at)%> ago </td>
        <td><%= time_ago_in_words(room.updated_at)%> ago </td>
<<<<<<< HEAD
        <td><%= image_tag room.avatar.url(:thumb) %></td>
=======
        <td><%= image_tag room.avatar.url(:medium) %></td>
>>>>>>> dce26c2f005a04950d404bd3be009bc50f2e0b5f
       <td><%= link_to 'Show', room %></td>
       <td><%= link_to 'Edit', edit_room_path(room) %></td>
       <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
     </tr>
   <% end %>
 
 </tbody>
</table>

</br>
</br>

<div id="map"></div>
  <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCHOnCFKBdLisShrN4r41bfyqR02ZWZ6Bs&callback=initMap">
    </script>
    <script>
      function initMap() {
        var uluru = {lat: 14.5651063, lng: 120.9939266 };
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 10,
          center: uluru
        });
        <% @rooms.each do |room| %>
        var marker = new google.maps.Marker({
          position: {lat:<%= room.latitude %>, lng: <%= room.longitude %>},
          map: map
        });
        <% end %>

      }
    </script>
    

</br>


<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'View Available Rooms', rooms_path %>

app/views/rooms/show.html.erb
</br>
</br>


<div id="map"></div>
    <script>
      function initMap() {
        var uluru = {lat: <%= @room.latitude %>, lng: <%= @room.longitude %>};
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 10,
          center: uluru
        });
        var marker = new google.maps.Marker({
          position: uluru,
          map: map
        });
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCHOnCFKBdLisShrN4r41bfyqR02ZWZ6Bs&callback=initMap">
    </script>

<h3>Nearby</h3>
    <div class="row">
      <% for room in @room.nearbys(10) %>
       <li><%= link_to room.location, room %> (<%= room.distance.round(2) %> kilometers away) </li>
<% end %>
       <td><%= image_tag room.avatar.url(:thumb) %></td>
   </div>


 </br>
   </br>






<div id="map"></div>
    <script>
      function initMap() {
        var uluru = {lat: <%= @room.latitude %>, lng: <%= @room.longitude %>};
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 10,
          center: uluru
        });
        var marker = new google.maps.Marker({
          position: uluru,
          map: map
        });
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCHOnCFKBdLisShrN4r41bfyqR02ZWZ6Bs&callback=initMap">
    </script>

<h3>Nearby</h3>
    <div class="row">
      <% for room in @room.nearbys(10) %>
       <li><%= link_to room.location, room %> (<%= room.distance.round(2) %> kilometers away) </li>
<% end %>
   </div>

   </br>
   </br>




<p>
  <strong>Photo:</strong>
  <%= image_tag(@room.avatar.url(:medium)) %>
</p>

<p>
  <strong>Host Name:</strong>
  <%= @room.host_name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @room.price %>
</p>


<p>
  <strong>Room name:</strong>
  <%= @room.room_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @room.description %>
</p>

<p>
  <strong>Country:</strong>
  <%= @room.country %>
</p>

<p>
  <strong>Location:</strong>
  <%= @room.location %>
</p>

<p>
  <strong>Bed:</strong>
  <%= @room.bed %>
</p>

<p>
  <strong>Bathroom:</strong>
  <%= @room.bathroom %>
</p>

<p>
<strong>Capacity:</strong>
<%= @room.capacity %>
</p>

<p>
<strong>Pets:</strong>
<%= @room.pets %>
</p>

<p>
<strong>Smoking:</strong>
<%= @room.smoking %>
</p>

<p>
<strong>Wifi:</strong>
<%= @room.wifi %>
</p>

<%= render 'bookings/form', booking: @booking %>


<p> AVERAGE RATING <p>
<div class="average-review-rating" data-score=<%= @average_review %>></div>
<span> Based on <%=@room.reviews.count %> review/s </span>
</p>


<!-- Review & Ratings -->
</br>
</br>

<%= render @room.reviews %>

<div>
  <%= link_to "Add Review", new_room_review_path(@room) %>
</div>


<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>

<script>
   $('.review-rating').raty({
     readOnly: true,
     score: function() {
       return $(this).attr('data-score');
     }
   });
 </script>

 <script>
   $('.average-review-rating').raty({
     readOnly: true,
     score: function() {
       return $(this).attr('data-score')
     }
   });
 </script>