config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :rooms do
  	resources :reviews
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations" }
  root 'pages#info'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_room
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]

  # GET /reviews
  # GET /reviews.json

  # GET /reviews/1
  # GET /reviews/1.json


  # GET /reviews/new
  def new
    @review = Review.new
  end


  # GET /reviews/1/edit
  def edit
    if current_user.id == @booking.user.id
      @review.edit
        redirect_to room_path(@room)
    else 
      "This is not your post"
end
end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.room_id = @room.id
    @review.user_id = current_user.id
    if @review.save
      redirect_to room_path(@room)
    else
      render 'new'
    end
  end


  def update
    if @review.update(review_params)
      redirect_to room_path(@room)
    else
      render 'edit'
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    if current_user.id == @booking.user.id
      @review.destroy
        redirect_to room_path(@room)
    else 
      "This is not your post"
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment)
    end

    def find_room
      @room = Room.find(params[:room_id])
    end

    def find_review
      @review = Review.find(params[:id])
    end
  end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for([@room, @room.reviews.build]) do |f| %>

<div id="rating-form">
  <label>Ratings</label>
</div>

<div class="field">
  <%= f.label :comment %><br />
  <%= f.text_area :comment %>
</div>

<div class="field">
  <%= f.submit %>
</div>
<% end %>

<script>
  $('#rating-form').raty({
     scoreName: 'review[rating]'
   });
   </script>

app/views/reviews/_review.html.erb
<div class= "review-rating" data-score= "<%= review.rating %>"></div>
<p><%= review.comment %></p>

<% if user_signed_in? %>
    <% if review.user_id == current_user.id %>
        <%= link_to "Edit", edit_room_review_path(review.room, review) %>
        <%= link_to "Delete", room_review_path(review.room, review), method: :delete, data: {confirm: "Are you sure?"} %>
   
   <% end %>
 <% end %>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= form_for([@room, @review]) do |f| %>
     <div id="rating-form">
       <label>Ratings</label>
     </div>
     
     <div class="field">
        <%= f.label :comment %><br />
        <%= f.text_area :comment %>
     </div>
 
     <div class="field">
        <%= f.submit %>
     </div>
    <% end %>
    
  <script>
 $('#rating-form').raty({
  scoreName: 'review[rating]'
 });
</script>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Rating</th>
      <th>Comment</th>
      <th>User</th>
      <th>Room</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.rating %></td>
        <td><%= review.comment %></td>
        <td><%= review.user_id %></td>
        <td><%= review.room_id %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>
<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<p>
  <strong>User:</strong>
  <%= @review.user_id %>
</p>

<p>
  <strong>Room:</strong>
  <%= @review.room_id %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>